config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :sup_sub_categories
  resources :sub_categories
  resources :categories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "products#index"
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
  validates :name, presence: true
  validates :number,presence: true, uniqueness: true
  belongs_to :category
  has_many :sup_sub_categories,dependent: :destroy
end

app/controllers/sub_categories_controller.rb
class SubCategoriesController < ApplicationController
  before_action :set_sub_category, only: %i[ show edit update destroy ]

  # GET /sub_categories or /sub_categories.json
  def index
    @sub_categories = SubCategory.all.order(number: :asc)
  end

  # GET /sub_categories/1 or /sub_categories/1.json
  def show
  end

  # GET /sub_categories/new
  def new
    @sub_category = SubCategory.new
  end

  # GET /sub_categories/1/edit
  def edit
  end

  # POST /sub_categories or /sub_categories.json
  def create
    @sub_category = SubCategory.new(sub_category_params)

    respond_to do |format|
      if @sub_category.save
        format.html { redirect_to sub_category_url(@sub_category), notice: "Sub category was successfully created." }
        format.json { render :show, status: :created, location: @sub_category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sub_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sub_categories/1 or /sub_categories/1.json
  def update
    respond_to do |format|
      if @sub_category.update(sub_category_params)
        format.html { redirect_to sub_category_url(@sub_category), notice: "Sub category was successfully updated." }
        format.json { render :show, status: :ok, location: @sub_category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sub_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_categories/1 or /sub_categories/1.json
  def destroy
    @sub_category.destroy

    respond_to do |format|
      format.html { redirect_to sub_categories_url, notice: "Sub category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sub_category
      @sub_category = SubCategory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sub_category_params
      params.require(:sub_category).permit(:number, :name, :category_id)
    end
end

app/helpers/sub_categories_helper.rb
module SubCategoriesHelper
end

app/views/sub_categories/_form.html.erb
<%= form_with(model: sub_category) do |form| %>
  <% if sub_category.errors.any? %>
    <div style="color: red">
      <ul>
        <% sub_category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :Número, style: "display: block" %>
    <%= form.text_field :number, class:"col-4" %>
  </div>

  <div>
    <%= form.label :Nombre, style: "display: block" %>
    <%= form.text_field :name, class:"col-4" %>
  </div>

  <div>
    <%= form.label :Categoría, style: "display: block" %>
    <%= form.collection_select :category_id, Category.all.order(number: :asc), :id, :name %>
  </div>
  <br>
  <div>
    <%= form.submit "Guardar", class: "btn btn-success"%>
  </div>
<% end %>

app/views/sub_categories/_sub_category.html.erb
<div id="<%= dom_id sub_category %>">
  <p>
    <strong>Número:</strong>
    <%= sub_category.number %>
  </p>

  <p>
    <strong>Nombre:</strong>
    <%= sub_category.name %>
  </p>

  <p>
    <strong>Categoría:</strong>
    <%= sub_category.category.name%>
  </p>

</div>

app/views/sub_categories/edit.html.erb
<h1>Editar sub categoría</h1>

<%= render "form", sub_category: @sub_category %>

<br>

<div>
  <%= link_to "Ver sub categoría", @sub_category, class: "btn btn-primary"%> |
  <%= link_to "Regresar a sub categorías", sub_categories_path, class: "btn btn-primary"%>
</div>

app/views/sub_categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Sub Categorías</h1>
<%= link_to "Nueva Sub Categoría", new_sub_category_path, class: "btn btn-primary" %>
<br>
<br>
<div class="table-responsive-xxl" id="business_sectors">
    <table class="table table-hover table-bordered ">
      <thead class="table-light">
        <tr>
        <th> Número </th>
        <th> Nombre </th>
        <th> Categoría </th>
        <th> Editar </th>
        <th> Elimnar</th>
        </tr>
      </thead>
      <tbody>
      <% @sub_categories.each do |sub_category| %>
            <tr>
              <td> <%= sub_category.number%> </td>
              <td> <%= sub_category.name%> </td>
              <td> <%= sub_category.category.name%> </td>
              <td> <%= link_to "Editar" , edit_sub_category_path(sub_category), class: "btn btn-primary"%> </td>
              <td> <%= button_to "Eliminar" , sub_category, method: :delete, class: "btn btn-danger" %> </td>
          <% end %>  
      </tbody>
    </table>  
</div>

app/views/sub_categories/new.html.erb
<h1>Nueva sub categoría</h1>

<%= render "form", sub_category: @sub_category %>

<br>

<div>
  <%= link_to "Regresar a sub categorías", sub_categories_path, class: "btn btn-primary" %>
</div>

app/views/sub_categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @sub_category %>

<div>
  <%= link_to "Editar sub categoría", edit_sub_category_path(@sub_category), class: "btn btn-primary" %> |
  <%= link_to "Regresar a sub categorías", sub_categories_path , class: "btn btn-primary"%>
  <br>
  <br>
  <%= button_to "Elimanr sub categoría", @sub_category, method: :delete, class: "btn btn-danger" %>
</div>