config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :sup_sub_categories
  resources :sub_categories
  resources :categories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "products#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vinneren</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" >
          <image_tag  alt="" width="30" height="24" class="d-inline-block align-text-top">
          <%= image_tag  "vinneren.png",alt:"" ,width:"120",height:"40" ,class:"d-inline-block align-text-top"%>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to products_path, class: "nav-link"  do %>
                <span>Productos</span>
              <%end%>
            </li>
            <li class="nav-item">
              <%= link_to categories_path, class: "nav-link"  do %>
                <span>Categorias</span>
              <%end%>
            </li>
            <li class="nav-item">
              <%= link_to sub_categories_path, class: "nav-link"  do %>
                <span>Sub Categorias</span>
              <%end%>
            </li>
            <li class="nav-item">
              <%= link_to sup_sub_categories_path, class: "nav-link"  do %>
                <span>Super Sub Categorias</span>
              <%end%>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <br>
    <br>
    <br>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>